import {exercises,characteristics,randomCase,simulate,parseCSV,compare,validate} from './exercise-models.js';
const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';
let selected=exercises[0],params,duration,rows=[],student=null,visible=new Set(),revision=0;
const fmt=x=>Number(x.toPrecision(4)).toString();
function node(tag,attrs,parent,text){const n=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;parent.append(n);return n;}
function notify(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function diagram(e){
 const electric=e.group==='Eléctricos';
 const resistor='<path d="M100 50h12l6-12 12 24 12-24 12 24 6-12h20"/>';
 const coil='<path d="M100 50h10c0-25 15-25 15 0c0-25 15-25 15 0c0-25 15-25 15 0h25"/>';
 const cap='<path d="M245 80v23m-20 0h40m-40 14h40m-20 0v23"/>';
 let drawing;
 if(electric){drawing=`<path d="M70 50h30m80 0h65v30m0 60v35${e.id==='rl'?'H70':'h-25m-80 0H70'}"/><circle cx="70" cy="50" r="4" fill="white"/><circle cx="70" cy="175" r="4" fill="white"/>${e.id==='rl'?resistor+'<g transform="translate(295 -20) rotate(90)">'+coil+'</g>':e.id==='rc'?resistor+cap:coil+cap}${e.id==='rl'?'':`<g transform="translate(320 225) rotate(180)">${e.id==='rc'?resistor:coil}</g>`}<path d="M82 66h35m-6-5 6 5-6 5" stroke="#00979d"/>`;
 }else{drawing=`<path d="M30 35v140h270V35" stroke="#8ca9ac"/><path d="M30 80h12l7-10 12 20 12-20 12 20 7-10h28"/><rect x="120" y="60" width="90" height="90" rx="8" fill="#d9edec"/><circle cx="137" cy="158" r="7"/><circle cx="193" cy="158" r="7"/>${e.id==='two'?'<path d="M210 100h10l7-10 12 20 12-20 12 20 7-10h30"/>':''}${e.id!=='spring'?'<path d="M30 128h40m0-9v18h28v-18H70m16 9h34"/>':''}<path d="M150 43h38m-7-5 7 5-7 5" stroke="#00979d"/>`;}
 $('diagram').innerHTML=`<svg viewBox="0 0 340 220" role="img" aria-label="${e.name}: esquema ideal"><g fill="none" stroke="#416d75" stroke-width="2.5" stroke-linejoin="round">${drawing}</g></svg>`;
 const svg=$('diagram').firstElementChild;
 const labels=electric?[[25,115,'Ve'],[95,90,'i →'],[130,25,e.id==='lc'?'L₁':e.id==='rc'?'R₁':'R'],[280,115,e.id==='rl'?'L':'C'],...(e.id==='rl'?[]:[[170,207,e.id==='rc'?'R₂':'L₂']])]:[[158,110,'m'],[65,58,e.id==='two'?'k₁':'k'],[158,28,'u →'],[214,53,'x →'],...(e.id!=='spring'?[[77,157,'b']]:[]),...(e.id==='two'?[[242,78,'k₂']]:[])];
 for(const [x,y,t]of labels)node('text',{x,y},svg,t);
}
function clearComparison(){student=null;$('importCSV').value='';$('comparisonStatus').textContent='Aún no has importado resultados.';$('comparisonStatus').classList.remove('error');$('metrics').replaceChildren();}
function fill(){for(const f of selected.fields)$('p-'+f.key).value=params[f.key];$('duration').value=duration;}
function select(e){selected=e;params={...e.defaults};duration=e.duration;visible=new Set(e.signals.map(s=>s[0]));
 document.querySelectorAll('[data-exercise]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.exercise===e.id)));
 $('exerciseName').textContent=e.name;$('category').textContent=e.group;$('order').textContent=e.order+'º orden';$('equation').textContent=e.equation;$('initial').textContent=e.initial;diagram(e);
 $('fields').replaceChildren();for(const f of e.fields){const label=document.createElement('label');label.textContent=f.label+' ('+f.unit+')';const input=document.createElement('input');Object.assign(input,{id:'p-'+f.key,type:'number',min:f.min,max:f.max,step:'any',required:true});label.append(input);$('fields').append(label);}
 $('hints').replaceChildren();e.hints.forEach((hint,i)=>{const details=document.createElement('details'),summary=document.createElement('summary'),p=document.createElement('p');summary.textContent='Pista '+(i+1);p.textContent=hint;details.append(summary,p);$('hints').append(details);});
 $('legend').replaceChildren();for(const [key,label,unit]of e.signals){const b=document.createElement('button');b.textContent=label+' · '+unit;b.setAttribute('aria-pressed','true');b.onclick=()=>{visible.has(key)?visible.delete(key):visible.add(key);b.setAttribute('aria-pressed',String(visible.has(key)));draw();};$('legend').append(b);}
 $('csvInstructions').textContent='Cabecera: t,'+e.signals.map(s=>s[0]).join(',')+'. Puedes incluir solo las señales que quieras comparar. Separador coma; decimales con punto.';
 $('matlabExample').textContent=`% Vectores columna exportados de tu modelo\nT = table(t(:), ${e.signals[0][0]}(:), 'VariableNames', {'t','${e.signals[0][0]}'});\nwritetable(T, 'mi_respuesta.csv');`;
 fill();calculate(params,duration);notify('Valores de la guía cargados. Entrada constante desde t = 0.');
}
function calculate(p,t){const next=simulate(selected,p,t);revision++;params={...p};duration=t;rows=next;clearComparison();const c=characteristics(selected,p);$('characteristic').textContent=c.tau?'Constante de tiempo τ = '+fmt(c.tau)+' s':'Frecuencia natural ωₙ = '+fmt(c.omega)+' rad/s · Amortiguamiento ζ = '+fmt(c.zeta)+(c.zeta===0?' · Oscilación ideal sin disipación':'');draw();}
function draw(){const root=$('plots');root.replaceChildren();for(const [key,label,unit]of selected.signals){if(!visible.has(key))continue;const section=document.createElement('div');section.className='plot';const h=document.createElement('h3');h.textContent=label+' ('+unit+')';section.append(h);root.append(section);const svg=node('svg',{viewBox:'0 0 430 235',role:'img','aria-label':label+' en función del tiempo'},section);
 const imported=student?.filter(r=>r.t<=duration),values=rows.map(r=>r[key]);if(imported&&key in imported[0])for(const r of imported)values.push(r[key]);let lo=0,hi=0;for(const v of values){lo=Math.min(lo,v);hi=Math.max(hi,v);}let span=hi-lo||1;lo-=span*.08;hi+=span*.08;span=hi-lo;
 const X=t=>65+350*t/duration,Y=v=>195-175*(v-lo)/span;
 for(let n=0;n<=4;n++){const value=lo+span*n/4,y=Y(value);node('line',{x1:65,x2:415,y1:y,y2:y,stroke:'#e2ecec'},svg);node('text',{x:59,y:y+4,'text-anchor':'end'},svg,fmt(value));const t=duration*n/4;node('text',{x:X(t),y:215,'text-anchor':'middle'},svg,fmt(t));}node('text',{x:240,y:232,'text-anchor':'middle'},svg,'Tiempo (s)');
 const line=(data,color,dash)=>{const stride=Math.max(1,Math.ceil(data.length/1800));const sampled=data.filter((_,i)=>i%stride===0||i===data.length-1);node('path',{d:sampled.map((r,i)=>(i?'L':'M')+X(r.t).toFixed(2)+' '+Y(r[key]).toFixed(2)).join(' '),fill:'none',stroke:color,'stroke-width':2,...(dash?{'stroke-dasharray':'6 4'}:{})},svg);};line(rows,'#008e98');if(imported&&key in imported[0])line(imported,'#b16e36',true);
 }if(!root.children.length)root.innerHTML='<p class="empty">Activa una señal para mostrar su gráfico.</p>';}
function download(name,content,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
for(const group of ['Eléctricos','Mecánicos']){const h=document.createElement('h3'),container=document.createElement('div');h.textContent=group;$('exerciseList').append(h,container);for(const e of exercises.filter(e=>e.group===group)){const b=document.createElement('button');b.dataset.exercise=e.id;b.textContent=e.name;const small=document.createElement('small');small.textContent=e.order+'º orden';b.append(small);b.onclick=()=>select(e);container.append(b);}}
$('parameterForm').onsubmit=event=>{event.preventDefault();try{const p=Object.fromEntries(selected.fields.map(f=>[f.key,Number($('p-'+f.key).value)]));calculate(p,Number($('duration').value));notify('Respuesta calculada. Se retiró cualquier comparación anterior.');}catch(e){notify(e.message,true);}};
$('parameterForm').oninput=()=>notify('Hay cambios sin calcular. Los gráficos y exportaciones conservan el último ensayo calculado.');
$('randomize').onclick=()=>{try{const c=randomCase(selected);calculate(c.p,c.duration);fill();notify('Nuevo caso: parámetros positivos, escalas de tiempo compatibles y duración ajustada. Guarda el ejercicio para repetirlo.');}catch(e){notify(e.message,true);}};
$('restore').onclick=()=>select(selected);
$('exportCSV').onclick=()=>{const keys=['t',...selected.signals.map(s=>s[0])];download(selected.id+'-referencia.csv',keys.join(',')+'\n'+rows.map(r=>keys.map(k=>r[k]).join(',')).join('\n'),'text/csv');};
$('saveCase').onclick=()=>download(selected.id+'-ejercicio.json',JSON.stringify({format:'estabiliza-exercise',version:1,model:selected.id,parameters:params,duration,initial:'zero',input:'step-at-zero'},null,2),'application/json');
$('loadCase').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>20000)throw Error('El archivo de ejercicio es demasiado grande.');const c=JSON.parse(await file.text()),e=exercises.find(e=>e.id===c.model);if(c.format!=='estabiliza-exercise'||c.version!==1||!e||c.initial!=='zero'||c.input!=='step-at-zero'||!c.parameters)throw Error('Formato de ejercicio no compatible.');validate(e,c.parameters,c.duration);simulate(e,c.parameters,c.duration);select(e);calculate(Object.fromEntries(e.fields.map(f=>[f.key,c.parameters[f.key]])),c.duration);fill();notify('Ejercicio recuperado con sus parámetros y duración.');}catch(e){notify(e.message,true);}finally{event.target.value='';}};
$('importCSV').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>12000000)throw Error('El archivo debe pesar menos de 12 MB.');const before=revision,text=await file.text();if(before!==revision)throw Error('El ejercicio cambi? durante la importaci?n. Vuelve a cargar el CSV.');const next=parseCSV(text,selected);const results=selected.signals.map(([key,label,unit])=>({label,unit,result:compare(rows,next,key)})).filter(r=>r.result);student=next;$('metrics').innerHTML='<table><thead><tr><th>Señal</th><th>Error RMS</th><th>Error máximo</th></tr></thead><tbody></tbody></table>';for(const r of results){const tr=document.createElement('tr');for(const t of [r.label,fmt(r.result.rmse)+' '+r.unit,fmt(r.result.max)+' '+r.unit]){const td=document.createElement('td');td.textContent=t;tr.append(td);}$('metrics').querySelector('tbody').append(tr);}$('comparisonStatus').textContent=file.name+' · '+next.length+' muestras. Diferencias evaluadas en los tiempos de la referencia.';$('comparisonStatus').classList.remove('error');draw();}catch(e){$('comparisonStatus').textContent=e.message+' La comparación anterior, si existe, se conserva.';$('comparisonStatus').classList.add('error');}finally{event.target.value='';}};
$('clearCSV').onclick=()=>{clearComparison();draw();};
select(selected);
